### ISSUE TITLE
turn this into a code along

### ISSUE THREAD

**Issue by jsms90** [shiryz/pg-walkthrough#15]
Relates https://github.com/foundersandcoders/master-reference/issues/290

@macintoshhelper Have a look at the [node intro workshop](https://github.com/foundersandcoders/Node-Intro-Workshop/tree/mentor-walkthrough) for inspiration on layout.

You probably want folders like `step 1`, `step 2`, etc, which contain the files as they should look after each step of the code along.

This should help:
+ students to go through it again step by step afterwards
+ students who have joined in late and need to catch up
+ yourself to prepare
+ yourself as a fallback in case you make a typo under pressure and can't figure out where it is (last resort)

This is extremely urgent, since this is going to be delivered next week. Please say now if you require help!

(In an ideal world, you might make a [video like @oliverjam has done for week 2](https://www.youtube.com/watch?v=7qEXPwG71RI&feature=youtu.be), so that future mentors / mentors in other campuses could use this to practice.)

**Comment by mattlub** [comment]
closing as this was done
