### ISSUE TITLE
write tests in this code along

### ISSUE THREAD

**Issue by jsms90** [shiryz/pg-walkthrough#18]
One of the big problems during FAC10 was that people didn't understand how to write tests for their database queries.

You can see there are no database tests in most week 6 projects. Only tests for the same things as week 5:
+ https://github.com/FAC10/week6-zapo/tree/master/tests
+ https://github.com/FAC10/week-6-jajascript/tree/master/tests
+ https://github.com/yvonne-liu/week6-soFly-FACt/tree/master/tests

Except this team, who checks whether the response from their `getData` query is of the right type:
+ https://github.com/smarthutza/week6-AMMPazon/blob/master/test-database/tests.js

By the end of week 7, their [SGC](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-7.md#go) shows:
> ### Go
> Travis setup with test database - nobody knows how to do it

There has now been a lot of confusion around testing during the node weeks for FAC11.

+ [ ] Add tests to this code along
+ [ ] Walk through the Travis set up

The [FAC9 research on testing](https://github.com/foundersandcoders/postgres-workshop) is pretty useful

**Comment by mattlub** [comment]
@jsms90 can we close this? There is a db testing workshop scheduled on the same day as this now in the MR: https://github.com/foundersandcoders/master-reference/tree/master/coursebook/week-6#day-2

**Comment by oliverjam** [comment]
Yeah we've had a DB-testing workshop for a while so this should be good. I don't think there'd be time for testing in this codealong anyway
